#!/bin/sh
#

if [ ! -x /usr/sbin/sshd ]; then
    apt install -y openssh-server
fi

if [ ! -d /run/sshd ]; then
    mkdir /run/sshd && chown root /run/sshd
fi

#####################################################################

if ! grep -q 'PermitRootLogin yes' /etc/ssh/sshd_config; then
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
    sed -ri 's/^UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    # echo 'root:root' | chpasswd
fi
