#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

#####################################################################

app_prepare() {

    if [ ! -x /usr/bin/php7 ]; then
        apk add php7 php7-fpm \
            php7-opcache \
            php7-session \
            php7-iconv php7-mbstring \
            php7-bcmath php7-calendar \
            php7-openssl php7-curl php7-sockets \
            php7-dom php7-xml php7-simplexml php7-json \
            php7-pdo php7-pdo_mysql php7-pdo_pgsql php7-pdo_sqlite \
            php7-mysqli php7-pgsql php7-sqlite3 php7-pecl-redis \
            php7-exif php7-gd php7-pecl-imagick \
            php7-bz2 php7-zip
    fi

    if ! grep -q $APP_GROUP /etc/group; then
        addgroup -S -g 82 $APP_GROUP
    fi

    if ! grep -q $APP_USER /etc/passwd; then
        adduser -S -D -h /var/www -s /sbin/nologin -G $APP_GROUP $APP_USER
    fi

    local DIR

    for DIR in log run tmp; do
        [ -d /var/$DIR/php7 ] ||
            mkdir -p /var/$DIR/php7
    done

    chown -R $APP_USER:$APP_GROUP /var/*/php7

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
