#!/bin/sh
#

webox=/opt/webox

#####################################################################

if [ ! -f $webox/etc/aulock ]; then
    date >$webox/etc/aulock
    if [ -d /overlay/etc ]; then
        cp -av /overlay/etc/* $webox/etc/
    fi
fi

if [ ! -f $webox/var/aulock ]; then
    date >$webox/var/aulock
    if [ -d /overlay/var ]; then
        cp -av /overlay/var/* $webox/var/
    fi
fi

#####################################################################

if grep '^#!/bin' -qrl $webox/etc; then
    chmod +x `grep '^#!/bin' -rl $webox/etc`
fi

if [ -d $webox/etc/init.d ]; then
    run-parts -a start $webox/etc/init.d
fi
