#!/bin/sh
#

webox=/opt/webox

if mount | grep -q $webox/etc-overlay; then
    cp -a $webox/etc-overlay/* $webox/etc/
    date >$webox/etc/aulock
fi

#####################################################################

$webox/cell/wkit/service "$@"
