#!/bin/sh
#

webox=/opt/webox

#####################################################################

if [ -d /overlay/etc ]; then
    date >$webox/etc/aulock
    cp -a /overlay/etc/* $webox/etc/
fi

#####################################################################

$webox/cell/wkit/service "$@"
