#!/bin/sh -e
#

chmod +x `grep -rl '^#!/bin' /ifs`

cp -a /ifs/usr /

for NAME in $WBX_APPS; do
    install=/usr/wkit/bundles/$NAME-add
    $install && rm -f $install
done

cp -a /ifs/etc /
cp -a /ifs/var /

rm -r /ifs
