#!/bin/sh -e
#

chmod +x `grep -rl '^#!/bin' /ifs`

# install apps

cp -a /ifs/usr /

for NAME in $WBX_APPS; do
    install=/usr/wkit/bundles/$NAME-add
    $install && rm -f $install
done

cp -a /ifs/etc /
cp -a /ifs/var /

# clean system

rm -f `grep openrc -rl /etc/init.d`
rm -f /var/cache/apk/*.tar.gz

rm -r /ifs
