#!/bin/sh
#

export APP_USER=mysql
export APP_GROUP=mysql

export APP_ETC_PATH=/srv/etc/mysql

#####################################################################

if [ ! -x /usr/bin/mysql ]; then
    apk add mariadb mariadb-client
fi

if [ ! -d /var/log/mysql ]; then
    mkdir -p /var/log/mysql
    chown -R $APP_USER:$APP_GROUP /var/log/mysql
fi

if [ ! -f /var/lib/mysql/ibdata1 ]; then
    mysql_install_db --user=$APP_USER --datadir=/var/lib/mysql
fi

chown -R $APP_USER:$APP_GROUP /var/lib/mysql

#####################################################################

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/mysql/etc $APP_ETC_PATH
fi

if ! grep -q $APP_ETC_PATH /etc/my.cnf; then
    sed -ri "s#^!includedir.+#!includedir $APP_ETC_PATH#" /etc/my.cnf
fi
