#!/bin/sh
#

if [ ! -x /usr/bin/mysql ]; then
    apk add mariadb mariadb-client
fi

if [ ! -d /var/log/mysql ]; then
    mkdir -p /var/log/mysql
    chown -R mysql:mysql /var/log/mysql
fi

if [ ! -f /var/lib/mysql/ibdata1 ]; then
    mysql_install_db --user=mysql --datadir=/var/lib/mysql
fi

chown -R mysql:mysql /var/lib/mysql

#####################################################################

export APP_ETC_PATH=/srv/etc/mysql

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/mysql/etc $APP_ETC_PATH
fi

if ! grep -q $APP_ETC_PATH /etc/my.cnf; then
    sed -ri "s#^!includedir.+#!includedir $APP_ETC_PATH#" /etc/my.cnf
fi
