#!/bin/sh
#

export APP_BIN_FILE=/usr/bin/mysqld_safe
export APP_PID_FILE=/run/mysql/mysqld.pid

#####################################################################

app_start() {

    if app_check ; then
        echo "mysql is already running"
        exit 1
    fi

    echo "start mysql ..."

    $APP_BIN_FILE --defaults-file=/srv/etc/mysql/my.cnf >/dev/null &

}

app_stop() {

    if ! app_check ; then
        echo "mysql is not running"
        exit 1
    fi

    echo "stop mysql ..."

    kill -TERM `cat $APP_PID_FILE`

}

app_reload() {

    if ! app_check ; then
        echo "mysql is not running"
        exit 1
    fi

    echo "reload mysql ..."

    kill -HUP `cat $APP_PID_FILE`

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_check
    app_result 'status:' 'running' 'stopped'

}

app_check() {

    if [ ! -f $APP_PID_FILE ] ; then
        return 1
    fi

    if ! kill -0 `cat $APP_PID_FILE` 2>/dev/null ; then
        rm -f $APP_PID_FILE
        return 1
    fi

}

app_usage() {

    local DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: wkit mysql {$DOES}"
        exit 1
    fi

}

app_result() {

    local CODE=$?
    local RIGHT=${2:-done}
    local ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo -e "$1 mysql \033[32m$RIGHT \033[0m"
    else
        echo -e "$1 mysql \033[31m$ERROR \033[0m"
    fi

    exit $CODE

}

#####################################################################

app_usage $1 || exit 1

app_$1
app_result $1
