#!/bin/sh
#

export APP_USER=nginx
export APP_GROUP=nginx

#####################################################################

app_prepare() {

    if [ ! -x /usr/bin/nginx ]; then
        apk add nginx \
            nginx-mod-http-echo \
            nginx-mod-http-cache-purge \
            nginx-mod-http-image-filter \
            nginx-mod-http-js \
            nginx-mod-stream \
            nginx-mod-stream-js
    fi

    local DIR

    for DIR in log run tmp; do
        [ -d /var/$DIR/nginx ] ||
            mkdir -p /var/$DIR/nginx
    done

    if [ ! -d /var/tmp/nginx/proxy_cache ]; then
        mkdir -p /var/tmp/nginx/proxy_cache
    fi

    chown -R $APP_USER:$APP_GROUP /var/*/nginx

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
