#!/bin/sh
#

export OPT_VERSION=1

export PATH=/opt/bin:$PATH

#####################################################################

if [ ! -x /opt/share/runtime ]; then
    chmod +x /opt/share/*/prepare
    chmod +x /opt/share/*/service
    chmod +x /opt/share/runtime
fi

opt_app_run() {

    local OPT_APP=$1
    local OPT_ACTION=$2
    local OPT_SCRIPT=/opt/share/$1

    case $OPT_ACTION in
        prepare)
            OPT_SCRIPT=$OPT_SCRIPT/prepare
        ;;
        *)
            OPT_SCRIPT=$OPT_SCRIPT/service
        ;;
    esac

    if [ ! -x $OPT_SCRIPT ]; then
        echo "can't exec $OPT_SCRIPT"
        exit 1
    fi

    $OPT_SCRIPT $OPT_ACTION

}

opt_fix_install() {

    local OPT_APP OPT_APP_EXTRA

    for OPT_APP_EXTRA in /opt/share/*; do

        OPT_APP=${OPT_APP_EXTRA##*/}

        if [ ! -x $OPT_APP_EXTRA/prepare ]; then
            continue
        fi

        if [ ! -e /opt/etc/$OPT_APP ] && [ -d $OPT_APP_EXTRA/etc ]; then
            ln -s ../share/$OPT_APP/etc /opt/etc/$OPT_APP
        fi

        echo "exec $OPT_APP_EXTRA/prepare"
        $OPT_APP_EXTRA/prepare prepare

    done

}
