#!/bin/sh -e
#

apk add --no-cache php81 php81-fpm \
    php81-bcmath \
    php81-bz2 \
    php81-curl \
    php81-ctype \
    php81-dom \
    php81-exif \
    php81-fileinfo \
    php81-ftp \
    php81-gd \
    php81-gettext \
    php81-iconv \
    php81-json \
    php81-mbstring \
    php81-mysqli \
    php81-mysqlnd \
    php81-opcache \
    php81-openssl \
    php81-pecl-redis \
    php81-pdo_mysql \
    php81-pdo_sqlite \
    php81-session \
    php81-shmop \
    php81-simplexml \
    php81-sockets \
    php81-sqlite3 \
    php81-tokenizer \
    php81-xml \
    php81-xmlreader \
    php81-xmlwriter \
    php81-xsl \
    php81-zip

rm -rf /etc/php81/php-fpm.d
rm -rf /var/lib/php81
