#!/bin/sh -e
#

apk add --no-cache php8 php8-fpm \
    php8-bcmath \
    php8-bz2 \
    php8-curl \
    php8-ctype \
    php8-dom \
    php8-exif \
    php8-fileinfo \
    php8-ftp \
    php8-gd \
    php8-gettext \
    php8-iconv \
    php8-json \
    php8-mbstring \
    php8-mysqli \
    php8-mysqlnd \
    php8-opcache \
    php8-openssl \
    php8-pecl-redis \
    php8-pdo_mysql \
    php8-pdo_sqlite \
    php8-session \
    php8-shmop \
    php8-simplexml \
    php8-sockets \
    php8-sqlite3 \
    php8-tokenizer \
    php8-xml \
    php8-xmlreader \
    php8-xmlwriter \
    php8-xsl \
    php8-zip

rm -rf /etc/php8/php-fpm.d
rm -rf /var/lib/php8
