#!/bin/sh -e
#

cd /tmp

apk add --no-cache --virtual build-deps \
    build-base curl-dev openssl-dev php8-pear php8-dev

pecl channel-update pecl.php.net

pecl bundle swoole

cd swoole && phpize

./configure \
    --enable-sockets \
    --enable-openssl \
    --enable-http2 \
    --enable-mysqlnd \
    --enable-swoole-json \
    --enable-swoole-curl

make
make install

strip /usr/lib/php8/modules/swoole.so

apk del build-deps
rm -rf /tmp/*

#====================================================================#

echo "extension=swoole.so" > /etc/php8/conf.d/50_swoole.ini
