#!/bin/sh -e
#

if [ ! -x /usr/sbin/sshd ]; then
    apk add --no-cache openssh
    ssh-keygen -t dsa -P "" -f /etc/ssh/ssh_host_dsa_key
    ssh-keygen -t rsa -P "" -f /etc/ssh/ssh_host_rsa_key
    ssh-keygen -t ecdsa -P "" -f /etc/ssh/ssh_host_ecdsa_key
    ssh-keygen -t ed25519 -P "" -f /etc/ssh/ssh_host_ed25519_key
fi

if echo "$@" | grep -q 'permit-root'; then
    if ! grep -q 'PermitRootLogin yes' /etc/ssh/sshd_config; then
        sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        sed -ri 's/^UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    fi
fi

rm -rf /etc/local.d/ssh
