#!/bin/sh
#

if [ ! -f /srv/etc/version ]; then
    cp -au /mnt/backup/* /srv/
fi

#####################################################################

if [ -d /srv/etc/init.d ]; then
    run-parts /srv/etc/init.d
fi

if [ -x /srv/service ]; then
    /srv/service start
fi

#####################################################################

exec crond -f -c /etc/crontabs
