#!/bin/sh
#

export APP_USER=postgres
export APP_GROUP=postgres

export APP_ETC_PATH=/srv/etc/postgresql

#####################################################################

export PGUSER=$APP_USER
export PGDATA=/var/lib/postgresql/data

if [ ! -x /sbin/su-exec ]; then
    apk add su-exec
fi

if [ ! -x /usr/bin/postgres ]; then
    apk add postgresql postgresql-contrib
fi

if [ ! -d /run/postgresql ]; then
    mkdir /run/postgresql && chown $APP_USER /run/postgresql
fi

if [ ! -d /var/lib/postgresql ]; then
    mkdir /var/lib/postgresql && chown $APP_USER /var/lib/postgresql
fi

if [ ! -f $PGDATA/postgresql.conf ]; then
    date | md5sum | head -c 10 > /var/lib/postgresql/postgres.pw
    su-exec $APP_USER initdb --pwfile=/var/lib/postgresql/postgres.pw
fi

chown -R $APP_USER:$APP_GROUP /var/lib/postgresql

#####################################################################

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/postgresql/etc $APP_ETC_PATH
fi

if ! grep -q $APP_ETC_PATH $PGDATA/postgresql.conf; then
    echo -e "\ninclude = '${APP_ETC_PATH}/extra.conf'" >> $PGDATA/postgresql.conf
    echo -e "\nhost    all    all    0.0.0.0/0    md5" >> $PGDATA/pg_hba.conf
fi
