#!/bin/sh
#

export PGHOME=/var/lib/postgresql

export PGDATA=$PGHOME/data
export PGUSER=postgres

if [ ! -x /sbin/su-exec ]; then
    apk add su-exec
fi

if [ ! -x /usr/bin/postgres ]; then
    apk add postgresql postgresql-contrib
fi

if [ ! -d /run/postgresql ]; then
    mkdir /run/postgresql && chown $PGUSER /run/postgresql
fi

if [ ! -f $PGDATA/postgresql.conf ]; then
    mkdir -p $PGHOME && chown postgres $PGHOME
    date | md5sum | head -c 10 > $PGHOME/postgres.pw
    su-exec $PGUSER initdb --pwfile=$PGHOME/postgres.pw
fi

chown -R $PGUSER:$PGUSER $PGHOME

#####################################################################

export APP_ETC_PATH=/srv/etc/postgresql

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/postgresql/etc $APP_ETC_PATH
fi

if ! grep -q $APP_ETC_PATH $PGDATA/postgresql.conf; then
    echo -e "\ninclude = '${APP_ETC_PATH}/extra.conf'" >> $PGDATA/postgresql.conf
    echo -e "\nhost    all    all    0.0.0.0/0    md5" >> $PGDATA/pg_hba.conf
fi
