#!/bin/sh
#

export APP_USER=postgres
export APP_GROUP=postgres

#####################################################################

export PGUSER=$APP_USER
export PGDATA=/var/lib/postgresql/data

app_start() {

    su-exec $APP_USER pg_ctl -w start

    if [ -f /var/lib/postgresql/import.sql ]; then
        su-exec $APP_USER psql < /var/lib/postgresql/import.sql
        mv /var/lib/postgresql/import.sql /var/lib/postgresql/import.done
    fi

}

app_stop() {

    su-exec $APP_USER pg_ctl -w stop

}

app_reload() {

    su-exec $APP_USER pg_ctl -w reload

}

app_restart() {

    su-exec $APP_USER pg_ctl -w restart

}

#####################################################################

echo "${1} postgresql ..."
app_${@}

if [ ${?} -ne 0 ]; then
    echo "${1} postgresql failed"
fi
