#!/bin/sh
#

export APP_USER=postgres
export APP_GROUP=postgres

#####################################################################

export PGUSER=$APP_USER
export PGDATA=/var/lib/postgresql/data

app_start() {

    su-exec $APP_USER pg_ctl -w start

    if [ -f /var/lib/postgresql/import.sql ]; then
        su-exec $APP_USER psql < /var/lib/postgresql/import.sql
        mv /var/lib/postgresql/import.sql /var/lib/postgresql/import.done
    fi

}

app_stop() {

    su-exec $APP_USER pg_ctl -w stop

}

app_reload() {

    su-exec $APP_USER pg_ctl -w reload

}

app_restart() {

    su-exec $APP_USER pg_ctl -w restart

}

app_helper() {

    local DOES="start|stop|reload|restart"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: webox postgresql {$DOES}"
        exit 1
    fi

}

app_result() {

    if [ $? -eq 0 ]; then
        echo -e "$@ postgresql \033[32mdone \033[0m"
    else
        echo -e "$@ postgresql \033[31mfailed \033[0m"
    fi

}

#####################################################################

app_helper $1

echo "$1 postgresql ..."

app_$1
app_result $1
