#!/bin/sh
#

if mount | grep -q /opt/etc; then
    cp -a /opt/etc/* /srv/etc/
    date >/srv/etc/aulock
fi

#####################################################################

if [ ! -f /srv/etc/aulock ]; then
    cp -au /opt/etc/* /srv/etc/
    date >/srv/etc/aulock
fi

if [ ! -f /srv/var/aulock ]; then
    cp -au /opt/var/* /srv/var/
    date >/srv/var/aulock
fi

#####################################################################

if [ -d /srv/etc/init.d ]; then
    run-parts /srv/etc/init.d
fi

if [ -x /srv/service ]; then
    /srv/service start
fi

#####################################################################

exec crond -f
