#!/bin/sh
#

apk add --no-cache nginx \
    nginx-mod-http-image-filter \
    nginx-mod-stream

rm -rf /etc/init.d/nginx
rm -rf /var/lib/nginx/*
rm -rf /var/www/localhost

ln -sf /var/run/nginx /var/lib/nginx/run
ln -sf /var/tmp/nginx /var/lib/nginx/tmp
ln -sf /var/log/nginx /var/lib/nginx/logs

ln -sf /usr/lib/nginx/modules /var/lib/nginx/modules
