#!/bin/sh -e
#

apk add --no-cache gcc g++ make
apk add --no-cache php7-pear php7-dev openssl-dev

pecl install swoole
strip /usr/lib/php7/modules/swoole.so

apk del gcc g++ make
apk del php7-pear php7-dev openssl-dev

#===========================================================#

echo "extension=swoole.so" > /etc/php7/conf.d/swoole.ini

apk add --no-cache php7-pcntl php7-posix
