#!/bin/sh -e
#

apk add --no-cache php7 php7-fpm \
    php7-bcmath \
    php7-bz2 \
    php7-curl \
    php7-ctype \
    php7-dom \
    php7-exif \
    php7-fileinfo \
    php7-ftp \
    php7-gd \
    php7-gettext \
    php7-iconv \
    php7-json \
    php7-mbstring \
    php7-mysqli \
    php7-mysqlnd \
    php7-opcache \
    php7-openssl \
    php7-pecl-redis \
    php7-pdo_mysql \
    php7-pdo_sqlite \
    php7-session \
    php7-shmop \
    php7-simplexml \
    php7-sockets \
    php7-sqlite3 \
    php7-tokenizer \
    php7-xml \
    php7-xmlreader \
    php7-xmlwriter \
    php7-xsl \
    php7-zip

rm -rf /etc/init.d/php7
rm -rf /etc/php7/php-fpm.d
rm -rf /var/lib/php7
