#!/bin/sh -e
#

apk add --no-cache --virtual build-deps \
    build-base openssl-dev php7-pear php7-dev

pecl channel-update pecl.php.net

pecl install swoole
strip /usr/lib/php7/modules/swoole.so

apk del build-deps

#====================================================================#

echo "extension=swoole.so" > /etc/php7/conf.d/swoole.ini

apk add --no-cache php7-pcntl php7-posix
