#!/bin/sh
#

export WBX_VERSION=1

export PATH=/opt/bin:$PATH

#####################################################################

if [ ! -x /opt/share/runtime ]; then
    chmod +x /opt/share/*/prepare
    chmod +x /opt/share/*/service
    chmod +x /opt/share/runtime
fi

wbx_app_run() {

    local WBX_APP=$1
    local WBX_ACTION=$2
    local WBX_SCRIPT=/opt/share/$1

    case $WBX_ACTION in
        prepare)
            WBX_SCRIPT=$WBX_SCRIPT/prepare
        ;;
        *)
            WBX_SCRIPT=$WBX_SCRIPT/service
        ;;
    esac

    if [ ! -x $WBX_SCRIPT ]; then
        echo "can't exec $WBX_SCRIPT"
        exit 1
    fi

    $WBX_SCRIPT $WBX_ACTION

}

wbx_fix_install() {

    local WBX_APP WBX_APP_EXTRA

    for WBX_APP_EXTRA in /opt/share/*; do

        WBX_APP=${WBX_APP_EXTRA##*/}

        if [ ! -x $WBX_APP_EXTRA/prepare ]; then
            continue
        fi

        if [ ! -e /opt/etc/$WBX_APP ] && [ -d $WBX_APP_EXTRA/etc ]; then
            ln -s ../share/$WBX_APP/etc /opt/etc/$WBX_APP
        fi

        echo "exec $WBX_APP_EXTRA/prepare"
        $WBX_APP_EXTRA/prepare prepare

    done

}
