#!/bin/sh
#

set -xe

apk update

#####################################################################

chmod +x /srv/webox/install

/srv/webox/install

#####################################################################

chmod +x /srv/init.sh
chmod +x /srv/webox/bin/*

rm -rf /var/cache/apk/*
rm -rf /var/log/*.log
rm -rf /var/lib/webox

rm -f /srv/webox/build
