#!/bin/sh
#

wbx_app_run() {

    local WBX_APP=$1
    local WBX_ACTION=$2
    local WBX_SCRIPT=/srv/share/$1

    case $WBX_ACTION in
        install)
            WBX_SCRIPT=$WBX_SCRIPT/install
        ;;
        start|stop|reload|restart)
            WBX_SCRIPT=$WBX_SCRIPT/service
        ;;
        *)
            WBX_SCRIPT=$WBX_SCRIPT/error
        ;;
    esac

    if [ ! -f $WBX_SCRIPT ]; then
        echo "NOT FOUND: $WBX_APP"
        exit 1
    fi

    [ -x $WBX_SCRIPT ] || chmod +x $WBX_SCRIPT
    $WBX_SCRIPT $WBX_ACTION

}

wbx_all_install() {

    local WBX_SCRIPT

    for WBX_SCRIPT in /srv/share/*/install; do
        [ -x $WBX_SCRIPT ] || chmod +x $WBX_SCRIPT
        echo "EXEC SCRIPT: $WBX_SCRIPT"
        $WBX_SCRIPT install
    done

}
