#!/bin/sh
#

export WBX_VERSION=1

export PATH=/srv/webox/bin:$PATH

if [ -z "$WBX_APPS" ]; then
    export WBX_APPS='nginx mysql redis php7'
fi

#####################################################################

if [ ! -x /srv/webox/runtime ]; then
    chmod +x /srv/webox/*/*
    chmod +x /srv/webox/*
fi

wbx_app_run() {

    local APP_NAME=$1
    local APP_ACTION=$2

    local APP_SCRIPT=/srv/webox/$1/service

    if [ ! -x $APP_SCRIPT ]; then
        echo "can't exec $APP_SCRIPT"
        exit 1
    fi

    $APP_SCRIPT $APP_ACTION

}

wbx_own_perm() {

    local APP_UID=${2:-0}
    local APP_GID=${3:-0}

    if [ -z $1 ] || [ ${#1} -lt 3 ] ; then
        echo "can't apply perm to this dir $1"
        exit 1
    fi

    chown -R $APP_UID:$APP_GID $1
    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;

}

wbx_fix_install() {

    local APP_NAME APP_EXDIR

    local APP_LIST="$@"
    if [ $# -eq 0 ]; then
        APP_LIST=`ls /srv/webox/`
    fi

    local ETC_TARGET=/srv/app/etc
    if [ ! -d $ETC_TARGET ]; then
        mkdir -p $ETC_TARGET
    fi

    for APP_NAME in $APP_LIST; do

        APP_EXDIR=/srv/webox/$APP_NAME

        if [ -d $APP_EXDIR/etc ]; then
            wbx_own_perm $APP_EXDIR/etc
            if [ ! -e $ETC_TARGET/$APP_NAME ]; then
                ln -s $APP_EXDIR/etc $ETC_TARGET/$APP_NAME
            fi
        fi

        if [ -x $APP_EXDIR/prepare ]; then
            echo "exec $APP_EXDIR/prepare"
            $APP_EXDIR/prepare prepare
        fi

    done

    echo $WBX_VERSION > $ETC_TARGET/version

}
