#!/bin/sh
#

if [ ! -x /usr/bin/php7 ]; then
    apk add php7 php7-fpm \
        php7-opcache \
        php7-session \
        php7-iconv php7-mbstring \
        php7-bcmath php7-calendar \
        php7-openssl php7-curl php7-sockets \
        php7-dom php7-xml php7-simplexml php7-json \
        php7-pdo php7-pdo_mysql php7-pdo_pgsql php7-pdo_sqlite \
        php7-mysqli php7-pgsql php7-sqlite3 php7-pecl-redis \
        php7-exif php7-gd php7-pecl-imagick \
        php7-bz2 php7-zip
fi

if ! grep -q www-data /etc/group; then
    addgroup -S -g 82 www-data
fi

if ! grep -q www-data /etc/passwd; then
    adduser -S -D -h /var/www -s /sbin/nologin -G www-data www-data
fi

if [ ! -d /run/php7 ]; then
    mkdir /run/php7 && chown www-data /run/php7
fi

#####################################################################

export APP_ETC_PATH=/srv/etc/php7

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/php7/etc $APP_ETC_PATH
fi
