#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

export APP_ETC_PATH=/srv/etc/php7

#####################################################################

if [ ! -x /usr/bin/php7 ]; then
    apk add php7 php7-fpm \
        php7-opcache \
        php7-session \
        php7-iconv php7-mbstring \
        php7-bcmath php7-calendar \
        php7-openssl php7-curl php7-sockets \
        php7-dom php7-xml php7-simplexml php7-json \
        php7-pdo php7-pdo_mysql php7-pdo_pgsql php7-pdo_sqlite \
        php7-mysqli php7-pgsql php7-sqlite3 php7-pecl-redis \
        php7-exif php7-gd php7-pecl-imagick \
        php7-bz2 php7-zip
fi

if ! grep -q $APP_GROUP /etc/group; then
    addgroup -S -g 82 $APP_GROUP
fi

if ! grep -q $APP_USER /etc/passwd; then
    adduser -S -D -h /var/www -s /sbin/nologin -G $APP_GROUP $APP_USER
fi

if [ ! -d /run/php7 ]; then
    mkdir /run/php7 && chown $APP_USER /run/php7
fi

#####################################################################

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/php7/etc $APP_ETC_PATH
fi
