#!/bin/sh
#

export APP_NAME=php7

export APP_USER=www-data
export APP_GROUP=www-data

export APP_ETC_PATH=/srv/etc/php7
export APP_PID_FILE=/run/php7/fpm.pid

#####################################################################

app_init() {

    local POOL_CONF POOL_PATH

    if [ -z $1 ] || [ ! -d $1 ]; then
        return 1
    fi

    for POOL_CONF in $1/*.conf; do

        POOL_CONF=${POOL_CONF##*/}
        POOL_PATH=/var/www/${POOL_CONF/.conf/}

        mkdir -p $POOL_PATH/log $POOL_PATH/temp
        mkdir -p $POOL_PATH/session $POOL_PATH/web

        chown -R $APP_USER:$APP_GROUP $POOL_PATH

    done

}

app_start() {

    if app_check ; then
        echo "$APP_NAME is already running"
        exit 1
    fi

    echo "start $APP_NAME ..."

    app_init $APP_ETC_PATH/fpm.d

    php-fpm7 -c $APP_ETC_PATH -y $APP_ETC_PATH/fpm.conf

}

app_stop() {

    if ! app_check ; then
        echo "$APP_NAME is not running"
        exit 1
    fi

    echo "stop $APP_NAME ..."

    kill -TERM `cat $APP_PID_FILE`

}

app_reload() {

    if ! app_check ; then
        echo "$APP_NAME is not running"
        exit 1
    fi

    echo "reload $APP_NAME ..."

    kill -USR2 `cat $APP_PID_FILE`

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_check
    app_result 'status:' 'running' 'stopped'

}

app_check() {

    if [ ! -f ${APP_PID_FILE} ] ; then
        return 1
    fi

    if ! kill -0 `cat ${APP_PID_FILE}` 2>/dev/null ; then
        rm -f ${APP_PID_FILE}
        return 1
    fi

}

app_usage() {

    local DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: webox $APP_NAME {$DOES}"
        exit 1
    fi

}

app_result() {

    local CODE=$?
    local RIGHT=${2:-done}
    local ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo -e "$1 $APP_NAME \033[32m$RIGHT \033[0m"
    else
        echo -e "$1 $APP_NAME \033[31m$ERROR \033[0m"
    fi

    exit $CODE

}

#####################################################################

app_usage $1 || exit 1

app_$1
app_result $1
