#!/bin/sh
#

export APP_USER=www-data
export APP_GROUP=www-data

export APP_ETC_PATH=/srv/etc/php7
export APP_PID_FILE=/run/php7/fpm.pid

#####################################################################

app_init() {

    local POOL_CONF POOL_PATH

    if [ -z $1 ] || [ ! -d $1 ]; then
        return 1
    fi

    for POOL_CONF in $1/*.conf; do

        POOL_CONF=${POOL_CONF##*/}
        POOL_PATH=/var/www/${POOL_CONF/.conf/}

        mkdir -p $POOL_PATH/log $POOL_PATH/temp
        mkdir -p $POOL_PATH/session $POOL_PATH/web

        chown -R $APP_USER:$APP_GROUP $POOL_PATH

    done

}

app_start() {

    app_init $APP_ETC_PATH/fpm.d

    php-fpm7 -c $APP_ETC_PATH -y $APP_ETC_PATH/fpm.conf

}

app_stop() {

    kill -TERM `cat ${APP_PID_FILE}`

}

app_reload() {

    kill -USR2 `cat ${APP_PID_FILE}`

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_helper() {

    local DOES="start|stop|reload|restart"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: webox php7 {$DOES}"
        exit 1
    fi

}

#####################################################################

app_helper $1

echo "${1} php7 ..."
app_${@}

if [ ${?} -ne 0 ]; then
    echo "${1} php7 failed"
fi
