#!/bin/sh
#

if [ ! -x /usr/bin/nginx ]; then
    apk add nginx \
        nginx-mod-http-echo \
        nginx-mod-http-cache-purge \
        nginx-mod-http-image-filter \
        nginx-mod-http-js \
        nginx-mod-stream \
        nginx-mod-stream-js
fi

if [ ! -d /run/nginx ]; then
    mkdir /run/nginx && chown nginx /run/nginx
fi

#####################################################################

export APP_ETC_PATH=/srv/etc/nginx

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/nginx/etc $APP_ETC_PATH
fi
