#!/bin/sh
#

export APP_ETC_PATH=/srv/etc/nginx

#####################################################################

app_start() {

    nginx -c $APP_ETC_PATH/nginx.conf

}

app_stop() {

    nginx -s stop

}

app_reload() {

    nginx -s reload

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_helper() {

    local DOES="start|stop|reload|restart"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: webox nginx {$DOES}"
        exit 1
    fi

}

app_result() {

    if [ $? -eq 0 ]; then
        echo -e "$@ nginx \033[32mdone \033[0m"
    else
        echo -e "$@ nginx \033[31mfailed \033[0m"
    fi

}

#####################################################################

app_helper $1

echo "$1 nginx ..."

app_$1
app_result $1
