#!/bin/sh
#

export APP_BIN_FILE=/usr/sbin/nginx
export APP_PID_FILE=/var/run/nginx/nginx.pid

#####################################################################

app_start() {

    if app_check ; then
        echo "nginx is already running"
        exit 1
    fi

    echo "start nginx ..."

    $APP_BIN_FILE -c /opt/etc/nginx/nginx.conf

}

app_stop() {

    if ! app_check ; then
        echo "nginx is not running"
        exit 1
    fi

    echo "stop nginx ..."

    $APP_BIN_FILE -s stop

}

app_reload() {

    if ! app_check ; then
        echo "nginx is not running"
        exit 1
    fi

    echo "reload nginx ..."

    $APP_BIN_FILE -s reload

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_status() {

    app_check
    app_result 'status:' 'running' 'stopped'

}

app_check() {

    if [ ! -f $APP_PID_FILE ] ; then
        return 1
    fi

    if ! kill -0 `cat $APP_PID_FILE` 2>/dev/null ; then
        rm -f $APP_PID_FILE
        return 1
    fi

}

app_usage() {

    local DOES="start|stop|reload|restart|status"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: wkit nginx {$DOES}"
        exit 1
    fi

}

app_result() {

    local CODE=$?
    local RIGHT=${2:-done}
    local ERROR=${3:-failed}

    if [ $CODE -eq 0 ]; then
        echo -e "$1 nginx \033[32m$RIGHT \033[0m"
    else
        echo -e "$1 nginx \033[31m$ERROR \033[0m"
    fi

    exit $CODE

}

#####################################################################

app_usage $1 || exit 1

app_$1
app_result $1
