#!/bin/sh
#

export APP_ETC_PATH=/srv/etc/nginx

#####################################################################

app_start() {

    nginx -c $APP_ETC_PATH/nginx.conf

}

app_stop() {

    nginx -s stop

}

app_reload() {

    nginx -s reload

}

app_restart() {

    app_stop && sleep 3 && app_start

}

#####################################################################

echo "${1} nginx ..."
app_${@}

if [ ${?} -ne 0 ]; then
    echo "${1} nginx failed"
fi
