#!/bin/sh
#

set -xe

apt update
apt install -y wget

#####################################################################

tini=https://github.com/krallin/tini/releases/download/v0.19.0/tini

wget -O /bin/tini ${tini} && chmod +x /bin/tini

#####################################################################

cd ~

name=webox-linux-v12.tgz

wget -c -O ${name} http://get.vmlu.com/webox/${name}
tar -xf ${name} && rm ${name}

cp -a ~/srv/* /srv/
rm -r ~/srv

#####################################################################

sed -i 's/ln -s/cp -a/' /srv/app/mysql/prepare
sed -i 's/ln -s/cp -a/' /srv/app/nginx/prepare
sed -i 's/ln -s/cp -a/' /srv/app/php/prepare
sed -i 's/ln -s/cp -a/' /srv/app/redis/prepare

ln -s /srv/app/srvkit /sbin/wkit

chmod +x /srv/init.sh

#####################################################################

rm -rf /var/cache/apt/*
rm -rf /var/log/*.log
rm -rf /var/log/apt/*.log
rm -rf /var/lib/apt/lists/*

rm -f /srv/deploy
