#!/bin/sh
#

set -xe

apt update
apt install -y wget

#####################################################################

tini=https://github.com/krallin/tini/releases/download/v0.19.0/tini

wget -O /bin/tini ${tini} && chmod +x /bin/tini

#####################################################################

cd ~

name=webox-linux-v11.tgz

wget -c -O ${name} http://get.vmlu.com/webox/${name}?v11.1.2
tar -xf ${name} && rm ${name}

cp -a ~/srv/* /srv/
rm -r ~/srv

#####################################################################

echo ". /srv/webox/runtime" >> /root/.bashrc

sed -i 's/ln -s/cp -a/' /srv/webox/wbx_install
ln -s /srv/webox/bin/wkit /sbin/wkit

chmod +x /srv/init.sh

#####################################################################

rm -rf /var/cache/apt/*
rm -rf /var/log/*.log
rm -rf /var/log/apt/*.log
rm -rf /var/lib/apt/lists/*
rm -rf /var/lib/webox

rm -f /srv/deploy
