#!/bin/sh
#

set -xe

apt update
apt install -y wget

#####################################################################

tini=https://github.com/krallin/tini/releases/download/v0.19.0/tini

wget -O /bin/tini ${tini} && chmod +x /bin/tini

#####################################################################

cd ~

name=webox-linux-v12.tgz

wget -c -O ${name} http://get.vmlu.com/webox/${name}?v12.0.1
tar -xf ${name} && rm ${name}

cp -a ~/srv/* /srv/
rm -r ~/srv

#####################################################################

mkdir -p /mnt/backup

mv /srv/etc /srv/var /mnt/backup
mkdir -p /srv/etc /srv/var

chmod +x /srv/init.sh

#####################################################################

rm -rf /var/cache/apt/*
rm -rf /var/log/*.log
rm -rf /var/log/apt/*.log
rm -rf /var/lib/apt/lists/*

rm -f /srv/deploy
