#!/bin/sh
#

set -xe

apt update
apt install -y wget

#####################################################################

cd ~

name=Webox-$(uname -s)-$(uname -m)-v10.tgz

wget -c -O ${name} http://get.vmlu.com/webox/${name}?v10.2.2
tar -xf ${name} && rm ${name}

cp -a ~/srv/* /srv/
rm -r ~/srv

#####################################################################

sed -i 's/ln -s/cp -a/' /srv/webox/wbx_install
ln -s /srv/webox/bin/wkit /sbin/wkit

chmod +x /srv/init.sh

#####################################################################

rm -rf /var/cache/apt/*
rm -rf /var/log/*.log
rm -rf /var/log/apt/*.log
rm -rf /var/lib/apt/lists/*
rm -rf /var/lib/webox

rm -f /srv/webox/build
