#!/bin/sh
#

if [ -f /etc/apt/sources.list.d/backports.list ]; then
    echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
    apt update
fi

if [ ! -x /usr/bin/apt-extracttemplates ]; then
    apt install -y apt-utils
fi

#apt install -y iputils-ping vim wget cron

#####################################################################

if [ -n $WBX_VERSION ]; then
    . /srv/webox/runtime
fi

if [ ! -f /var/lib/webox/version ]; then
    mkdir -p /var/lib/webox
    echo 0 > /var/lib/webox/version
fi

if [ `cat /var/lib/webox/version` -lt $WBX_VERSION ]; then
    echo $WBX_VERSION > /var/lib/webox/version
    wbx_fix_install
fi
