#!/bin/sh
#

if [ -f /etc/apt/sources.list.d/backports.list ]; then
    echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
    apt update
fi

if [ ! -x /usr/bin/apt-extracttemplates ]; then
    apt install -y apt-utils
fi

#apt install -y iputils-ping vim wget cron
