#!/bin/sh
#

set -xe

chmod +x `grep '^#!/bin' -rl /deploy`

cp -a /deploy/usr /

for NAME in mysql nginx php7 redis; do
    install=/usr/wkit/ports/$NAME-install
    $install && rm -f $install
done

cp -a /deploy/etc /
cp -a /deploy/var /

rm -r /deploy
