#!/bin/sh
#

set -xe

#####################################################################

cd ~

name=webox-linux-v10.tgz

wget -c -O ${name} http://get.vmlu.com/webox/${name}?v10.3.0
tar -xf ${name} && rm ${name}

rm -r ~/srv/etc/nginx/vhost.d/sample-host
rm -r ~/srv/var/www/default/*
cp -a ~/srv/* /srv/
rm -r ~/srv

#####################################################################

mkdir -p /mnt/backup

mv /srv/etc /srv/var /mnt/backup
mkdir -p /srv/etc /srv/var

#####################################################################

chmod +x /etc/webox/*

rm -f /deploy
