#!/bin/sh
#

set -xe

apt update
apt install -y wget

#####################################################################

wget -qO- http://get.vmlu.com/webox/wb-fetch | sh

sed -i 's/ln -s/cp -a/' ~/srv/webox/runtime

cp -a ~/srv/* /srv/
rm -r ~/srv

#####################################################################

chmod +x /srv/init.sh
chmod +x /srv/webox/bin/*

rm -rf /var/cache/apt/*
rm -rf /var/log/*.log
rm -rf /var/log/apt/*.log
rm -rf /var/lib/apt/lists/*
rm -rf /var/lib/webox

rm -f /srv/webox/build
