#!/bin/sh
#

export webox=/opt/webox

#####################################################################

if [ -d /overlay/etc ]; then
    cp -a /overlay/etc/* $webox/etc/
fi

$webox/cell/wkit/service "$@"
