#!/bin/sh -e
#

wget https://github.com/rehiy/webox-alpine/archive/refs/heads/master.tar.gz
tar xvf master.tar.gz && rm -f master.tar.gz

cd webox-alpine-master
sh install wkit-container mysql nginx nginx-php php8.2 redis

cd ~
rm -rf /tmp/*
