#!/bin/sh
#

. /usr/wkit/app-rc

#====================================================================#

APP_NAME=nginx

APP_USER=nginx
APP_GROUP=nginx

APP_BIN_FILE=/usr/sbin/nginx
APP_PID_FILE=/var/run/nginx/nginx.pid

#====================================================================#

app_stop() {

    $APP_BIN_FILE -s stop

}

app_reload() {

    $APP_BIN_FILE -s reload

}

app_prepare() {

    local SDIR

    app_varfix log run tmp

}

#====================================================================#

app_do $1
