#!/bin/sh
#

export APP_USER=redis
export APP_GROUP=redis

export APP_ETC_PATH=/srv/etc/redis

#####################################################################

if [ ! -x /sbin/su-exec ]; then
    apk add su-exec
fi

if [ ! -x /usr/bin/redis-server ]; then
    apk add redis
fi

chown -R $APP_USER:$APP_GROUP /var/lib/redis

#####################################################################

if [ ! -e $APP_ETC_PATH ]; then
    ln -s ../share/redis/etc $APP_ETC_PATH
fi

if ! grep -q $APP_ETC_PATH /etc/redis.conf; then
    echo -e "\ninclude ${APP_ETC_PATH}/redis.conf" >> /etc/redis.conf
fi
