#!/bin/sh
#

export APP_USER=redis
export APP_GROUP=redis

#####################################################################

app_prepare() {

    if [ ! -x /usr/bin/redis-server ]; then
        apk add redis
    fi

    for dir in lib log run tmp; do
        [ -d /var/${dir}/redis ] ||
            mkdir -p /var/${dir}/redis
    done

    if [ ! -f /srv/etc/redis/conf.d/useful.conf ]; then
        touch /srv/etc/redis/conf.d/useful.conf
    fi

    chown -R $APP_USER:$APP_GROUP /var/*/redis

}

#####################################################################

[ "$1" = "prepare" ] && app_prepare
