#!/bin/sh
#

export APP_USER=redis

export APP_PID_FILE=/run/redis/redis.pid

#####################################################################

app_start() {

    su-exec $APP_USER redis-server /etc/redis.conf

}

app_stop() {

    kill -TERM `cat $APP_PID_FILE`

}

app_reload() {

    kill -HUP `cat $APP_PID_FILE`

}

app_restart() {

    app_stop && sleep 3 && app_start

}

app_helper() {

    local DOES="start|stop|reload|restart"

    if ! echo "|$DOES|" | grep -q "|$1|"; then
        echo "Usage: webox redis {$DOES}"
        exit 1
    fi

}

app_result() {

    if [ $? -eq 0 ]; then
        echo -e "$@ redis \033[32mdone \033[0m"
    else
        echo -e "$@ redis \033[31mfailed \033[0m"
    fi

}

#####################################################################

app_helper $1

echo "$1 redis ..."

app_$1
app_result $1
