#!/bin/sh
#

export OPT_VERSION=1

export PATH=/opt/bin:$PATH

#####################################################################

if [ ! -x /opt/share/runtime ]; then
    chmod +x /opt/share/*/prepare
    chmod +x /opt/share/*/service
    chmod +x /opt/share/runtime
    chmod +x /opt/bin/*
fi

opt_app_run() {

    local OPT_APP=$1
    local OPT_ACTION=$2
    local OPT_SCRIPT=/opt/share/$1

    case $OPT_ACTION in
        prepare)
            OPT_SCRIPT=$OPT_SCRIPT/prepare
        ;;
        *)
            OPT_SCRIPT=$OPT_SCRIPT/service
        ;;
    esac

    if [ ! -x $OPT_SCRIPT ]; then
        echo "can't exec $OPT_SCRIPT"
        exit 1
    fi

    $OPT_SCRIPT $OPT_ACTION

}

opt_own_perm() {

    local OPT_UID=${2:-0}
    local OPT_GID=${3:-0}

    if [ -z $1 ] || [ ${#1} -lt 3 ] ; then
        echo "can't apply perm to this dir $1"
        exit 1
    fi

    find $1 \( ! -perm 0644 -type f \) -exec chmod 0644 {} \;
    find $1 \( ! -perm 0755 -type d \) -exec chmod 0755 {} \;
    find $1 ! \( -uid $OPT_UID -gid $OPT_GID \) -exec chown $OPT_UID:$OPT_GID {} \;

}

opt_fix_install() {

    local OPT_APP OPT_APP_EXTRA

    if [ ! -d /opt/etc ]; then
        mkdir -p /opt/etc
    fi

    for OPT_APP_EXTRA in /opt/share/*; do

        OPT_APP=${OPT_APP_EXTRA##*/}

        if [ -d $OPT_APP_EXTRA/etc ]; then
            opt_own_perm $OPT_APP_EXTRA/etc
            if [ ! -e /opt/etc/$OPT_APP ]; then
                ln -s ../share/$OPT_APP/etc /opt/etc/$OPT_APP
            fi
        fi

        if [ -x $OPT_APP_EXTRA/prepare ]; then
            echo "exec $OPT_APP_EXTRA/prepare"
            $OPT_APP_EXTRA/prepare prepare
        fi

    done

}
