#!/bin/sh
#

. /usr/wkit/app-rc

#====================================================================#

APP_NAME=mysql

APP_USER=mysql
APP_GROUP=mysql

APP_BIN_FILE=/usr/bin/mysqld_safe
APP_PID_FILE=/var/run/mysqld/mysqld.pid

#====================================================================#

app_start() {

    $APP_BIN_FILE >/dev/null &

}

app_prepare() {

    app_varfix lib log run tmp

    local MLOG=/var/log/mysql/error.log

    if [ ! -f $MLOG ]; then
        touch $MLOG && app_ownmod /var/log/mysql
    fi

    if [ ! -d /var/lib/mysql/mysql ]; then
        mysql_install_db --skip-test-db \
            --user=$APP_USER --datadir=/var/lib/mysql >$MLOG
    fi

}

#====================================================================#

app_do $1
